[tool.poetry]
name = "{{cookiecutter.package_name.replace('_', '-')}}"
version = "0.1.0"
description = ""
authors = ["author_name <author@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0.2"
Flask = "^3.1.0"
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"